export const COUNTRIES_GET_ALL = 'COUNTRIES_GET_ALL';
export const COUNTRIES_GET_ONE = 'COUNTRIES_GET_ONE';
export const COUNTRIES_DELETE_ONE = 'COUNTRIES_DELETE_ONE';
export const COUNTRIES_SEARCH = 'COUNTRIES_SEARCH';
export const COUNTRIES_SET_CONTINENT = 'COUNTRIES_SET_CONTINENT';
